"""
Tips Tool - History lookup for practice tips.

Tips are now generated by the tips subagent and shown in the tips panel.
This tool is for looking up previously given tips only.
"""

from agno.tools import tool

# History of tips given in this session
_tips_history: list[dict] = []


def record_tips(tips: dict):
    """Record tips that were shown to the user."""
    _tips_history.append(tips)


def get_tips_history() -> list[dict]:
    """Get all tips given in this session."""
    return _tips_history.copy()


def clear_tips_history():
    """Clear the tips history."""
    global _tips_history
    _tips_history = []


@tool
def get_practice_tips(practice_focus: str = "") -> dict:
    """Look up previously given practice tips.

    This tool checks if tips have already been generated for a topic.
    Tips are generated automatically by the tips subagent when setting up sessions.

    NOTE: Do NOT use this tool to generate tips - tips are generated
    automatically and shown in the tips panel. This is for history lookup only.

    Args:
        practice_focus: Optional filter by topic (e.g., "hands", "gestures")

    Returns:
        Dictionary with tips history or message if none found
    """
    if not _tips_history:
        return {
            "found": False,
            "message": "No tips have been generated yet. Tips are created when preparing a practice session.",
        }

    # Filter by focus if provided
    if practice_focus:
        focus_lower = practice_focus.lower()
        matching = [
            t for t in _tips_history
            if focus_lower in t.get("practice_focus", "").lower()
        ]
        if matching:
            return {
                "found": True,
                "tips": matching[-1],  # Most recent matching tips
                "total_history": len(_tips_history),
            }
        else:
            return {
                "found": False,
                "message": f"No tips found for '{practice_focus}'. Topics covered: {[t.get('practice_focus') for t in _tips_history]}",
            }

    # Return most recent tips
    return {
        "found": True,
        "tips": _tips_history[-1],
        "total_history": len(_tips_history),
    }
